---
- hosts: wordpress
  remote_user: carlos
  become: yes
- name: Executando Roles Para instalação do Wordpress
  roles:
    - server
    - php
    - mysql
    - wordpress

# exemplo
# agora estou fazendo uma alteracao na branch angular